import OBR from "@owlbear-rodeo/sdk";
import { clamp, loadState, META_KEY, MiruState, saveState } from "./state";
import { COMBAT_ITEMS, isWeapon, SLEEP_DEP_EP, STARVATION_HP, STEP_PAGE, WEATHER_BY_TERRAIN } from "./rules";

let state:MiruState|null=null,queued=false;
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
const d6=()=>Math.floor(Math.random()*6)+1;
const edge=(a:string,b:string)=>[a,b].sort().join("|");
async function commit(next:MiruState){state=next;await saveState(next);queuePatch();}
function injectStyle(){if(document.querySelector("#play-ready-style"))return;const s=document.createElement("style");s.id="play-ready-style";s.textContent=`.play-ready-actions{margin:10px 0;padding:10px;border:1px solid #6f6b65;background:#f0ece3;color:#19191b;display:grid;gap:7px}.play-ready-actions b{font-size:10px;letter-spacing:.08em}.play-ready-actions p{margin:0;font-size:9px;line-height:1.4}.play-ready-actions .row{display:flex;flex-wrap:wrap;gap:6px}.play-ready-actions button,.play-ready-actions input,.play-ready-actions select{font:inherit;border:1px solid #777;background:white;color:#19191b;border-radius:5px;padding:7px}.play-ready-actions button{font-size:8px;font-weight:900}.play-ready-warning{background:#ffe2dc!important;border-color:#b65049!important}.rules-lock{opacity:.45;pointer-events:none}.rules-lock-note{font-size:8px;padding:7px 10px;background:#ef554c;color:#fff;font-weight:900;letter-spacing:.06em}.derived-combat{margin:8px 0;padding:9px;border:1px dashed #8b857b;display:grid;gap:6px}.derived-combat label{font-size:8px;font-weight:900}.derived-combat select,.derived-combat input{width:100%;padding:7px}.impassable-control{margin-top:8px;width:100%}`;document.head.appendChild(s);}
function correctPageRefs(){document.querySelectorAll<HTMLElement>("button,span,small").forEach(el=>{const t=el.textContent??"";if((/^J\b/.test(t)||/^K\b/.test(t)||t.includes("STEP J")||t.includes("STEP K"))&&t.includes("p.8"))el.textContent=t.replace("p.8","p.7");});}
function patchLoadoutLock(){const allowed=state?.step==="D";document.querySelectorAll<HTMLButtonElement>("[data-equip],[data-unequip],[data-body-remove]").forEach(b=>{b.disabled=!allowed;b.classList.toggle("rules-lock",!allowed);});const body=document.querySelector<HTMLElement>(".body-paper");if(body){body.querySelector(".rules-lock-note")?.remove();if(!allowed){const n=document.createElement("div");n.className="rules-lock-note";n.textContent=`LOADOUT CHANGES HAPPEN AT STEP D · ${STEP_PAGE.D}`;body.querySelector("header")?.insertAdjacentElement("afterend",n);}}}
async function ensureThirdInjury(){if(!state)return false;const r=state.terrainRoll;if(r?.day===state.day&&r.result===1&&r.applied&&state.minorInjuries>=3&&!state.dayState.pendingAfterP&&state.step==="G"){await commit({...state,step:"O",dayState:{...state.dayState,pendingAfterP:"minor-injury-3"}});return true;}return false;}
function guideHost(){return document.querySelector<HTMLElement>("#guide-drawer")??document.querySelector<HTMLElement>(".guide-drawer");}
function actionBox(title:string,body:string){const box=document.createElement("section");box.className="play-ready-actions";box.innerHTML=`<b>${title}</b><p>${body}</p><div class="row"></div>`;return box;}
function btn(label:string,fn:()=>void){const b=document.createElement("button");b.textContent=label;b.onclick=fn;return b;}
function add(box:HTMLElement,...els:HTMLElement[]){const row=box.querySelector<HTMLElement>(".row")!;els.forEach(x=>row.appendChild(x));}
function patchGuide(){if(!state)return;const host=guideHost();if(!host)return;host.querySelector("#play-ready-guide")?.remove();const wrap=document.createElement("div");wrap.id="play-ready-guide";const step=state.step,terrain=state.mapHexes[state.currentHex]?.terrain??"";
 if(step==="H"){const box=actionBox("WEATHER · OPTIONAL · p.7",state.dayState.weather?`Recorded: ${state.dayState.weather} (roll ${state.dayState.weatherRoll}). Effects are carried into sleep/combat.`:`Roll 1d6 and use the current terrain's weather table.`);if(WEATHER_BY_TERRAIN[terrain])add(box,btn("ROLL + RECORD WEATHER",()=>{if(!state)return;const roll=d6(),weather=WEATHER_BY_TERRAIN[terrain](roll);void commit({...state,dayState:{...state.dayState,weather,weatherRoll:roll,sleepPossible:weather!=="Extreme Winds"}});}),btn("SKIP WEATHER",()=>{if(state)void commit({...state,dayState:{...state.dayState,weather:null,weatherRoll:null},step:"I"});}));else box.querySelector("p")!.textContent="Terrain must be recorded before weather can be resolved.";wrap.appendChild(box);}
 if(step==="L"){const total=state.supplies.Fruit+state.supplies["Meal Bar"],box=actionBox("EAT FOOD · p.8",`Meal Bars ${state.supplies["Meal Bar"]} · Fruit ${state.supplies.Fruit}. If Food is held, eat at least 1 and no more than 3 during Step L.`);const eaten=(state.dayState as any).foodEaten??0;const eat=(kind:"Fruit"|"Meal Bar")=>{if(!state||state.supplies[kind]<1||eaten>=3)return;const supplies={...state.supplies,[kind]:state.supplies[kind]-1};const hp=clamp(state.hp+(kind==="Meal Bar"?2:1),0,20),ep=clamp(state.ep+(kind==="Meal Bar"?1:2),0,20);void commit({...state,hp,ep,supplies,dayState:{...state.dayState,ate:true,...({foodEaten:eaten+1} as any)}});};if(total)add(box,btn("EAT MEAL BAR",()=>eat("Meal Bar")),btn("EAT FRUIT",()=>eat("Fruit")));add(box,btn(total===0?"NO FOOD → STEP N":"DONE EATING → STEP M",()=>{if(!state)return;if(total>0&&!state.dayState.ate){void OBR.notification.show("If you have Food, MIRU requires eating at least one item at Step L.","WARNING");return;}void commit({...state,step:total===0?"N":"M"});}));wrap.appendChild(box);}
 if(step==="N"){const blocked=!state.dayState.sleepPossible||state.dayState.weather==="Extreme Winds",gear=state.activeBody.includes("Improved Camping Gear"),base=gear?4:3,baseEp=gear?4:2,hpGain=state.dayState.weather==="Harsh Snow"?0:base,epGain=state.dayState.weather==="Heavy Rain"?0:baseEp,box=actionBox("ATTEMPT TO SLEEP · p.9",blocked?"Sleep is prevented. Skip to Step O.":`If you can Sleep, you must. Recovery now: +${hpGain} HP / +${epGain} EP${gear?" (Improved Camping Gear)":""}.`);if(blocked)add(box,btn("CONTINUE → STEP O",()=>{if(state)void commit({...state,dayState:{...state.dayState,slept:false},step:"O"});}));else add(box,btn("SLEEP",()=>{if(state)void commit({...state,hp:clamp(state.hp+hpGain,0,20),ep:clamp(state.ep+epGain,0,20),dayState:{...state.dayState,slept:true},step:"O"});}),btn("EVENT PREVENTS SLEEP",()=>{if(state)void commit({...state,dayState:{...state.dayState,sleepPossible:false,slept:false},step:"O"});}));wrap.appendChild(box);}
 if(step==="O"){const box=actionBox("CONDITION CHECK · p.9",`Apply in order. Starvation ${state.starvation}/8 · Sleep Deprivation ${state.sleepDeprivation}/5. Poison is MIRU 2 material and is not auto-resolved here.`);add(box,btn(state.dayState.conditionsApplied?"CONDITIONS APPLIED → STEP P":"APPLY CONDITION CHECK",()=>{if(!state)return;if(state.dayState.conditionsApplied){void commit({...state,step:"P"});return;}let starvation=state.dayState.ate?0:Math.min(8,state.starvation+1),sleep=state.dayState.slept?0:Math.min(5,state.sleepDeprivation+1),hp=state.hp,ep=state.ep;if(!state.dayState.ate){if(starvation>=8)hp=0;else hp=Math.max(0,hp-STARVATION_HP[starvation]);}if(!state.dayState.slept){if(sleep>=5)hp=0;else{const loss=SLEEP_DEP_EP[sleep],spill=Math.max(0,loss-ep);ep=Math.max(0,ep-loss);hp=Math.max(0,hp-spill);}}void commit({...state,hp,ep,starvation,sleepDeprivation:sleep,dayState:{...state.dayState,conditionsApplied:true}});}));wrap.appendChild(box);}
 if(step==="P"){const box=state.dayState.pendingAfterP==="minor-injury-3"?actionBox("3 MINOR INJURIES · p.21","After Step P resolve the injury event: lose half your Bits rounded down, remove duplicate non-Food items, reset HP/EP to 10, then begin the next day at Step A."):actionBox("END OF DAY · p.9","After moving any enemies, the day is complete. Continue at Step A.");if(state.dayState.pendingAfterP==="minor-injury-3")add(box,btn("RESOLVE p.21 AFTERMATH",()=>{if(!state)return;const inventory=Object.fromEntries(Object.entries(state.inventory).map(([k,v])=>[k,Math.min(1,v)]));const lost=Math.floor(state.supplies.Bits/2);void commit({...state,hp:10,ep:10,inventory,supplies:{...state.supplies,Bits:state.supplies.Bits-lost},step:"A",dayState:{...state.dayState,pendingAfterP:null}});}));else add(box,btn("DAY COMPLETE → STEP A",()=>{if(state)void commit({...state,step:"A"});}));wrap.appendChild(box);}
 if(["I","J","K"].includes(step)){const box=actionBox("EVENT MEMORY · p.13 / p.17","Events do not repeat. Record a short event ID (for example Forest R-03). If it is already recorded, use the next available event; if all options are exhausted, go to Step L.");const input=document.createElement("input");input.placeholder="Event ID";const mark=btn("MARK EXPERIENCED",()=>{if(!state)return;const id=input.value.trim();if(!id)return;if(state.experiencedEvents.includes(id)){void OBR.notification.show(`${id} is already experienced - use the next available event.`,"WARNING");return;}void commit({...state,experiencedEvents:[...state.experiencedEvents,id]});});add(box,input,mark);wrap.appendChild(box);}
 host.appendChild(wrap);}
function patchCombat(){if(!state)return;const fighter=document.querySelector<HTMLElement>(".fighter-card");if(!fighter)return;fighter.querySelector("#derived-combat")?.remove();const weapons=state.activeBody.filter(isWeapon),def=1+state.activeBody.reduce((n,x)=>n+(COMBAT_ITEMS[x]?.def??0),0)+(state.combat.robot&&state.mask==="Cyclops Mask"?1:0)-(state.dayState.weather==="Heavy Rain"?1:state.dayState.weather==="Harsh Snow"?2:0);const box=document.createElement("div");box.id="derived-combat";box.className="derived-combat";box.innerHTML=`<b>RULEBOOK-DERIVED LOADOUT</b><label>ATTACK WEAPON<select id="combat-weapon"><option value="">Fists / no weapon</option>${weapons.map(w=>`<option value="${esc(w)}" ${state!.combat.selectedWeapon===w?"selected":""}>${esc(w)} +${COMBAT_ITEMS[w]?.atk??0} ATK${COMBAT_ITEMS[w]?.weapon==="range"?" · 1 Arrow":""}</option>`).join("")}</select></label><span>DEF ${Math.max(0,def)} · Arrows ${state.supplies.Arrows} · Weather ${state.dayState.weather??"none"}</span><label>ENEMY SKILL / REWARD DICE<input id="enemy-skill" type="number" min="1" max="6" value="${state.combat.enemySkill}"></label>`;fighter.appendChild(box);box.querySelector<HTMLSelectElement>("#combat-weapon")!.onchange=e=>{if(state)void commit({...state,combat:{...state.combat,selectedWeapon:(e.target as HTMLSelectElement).value||null}});};box.querySelector<HTMLInputElement>("#enemy-skill")!.onchange=e=>{if(state)void commit({...state,combat:{...state.combat,enemySkill:clamp(Number((e.target as HTMLInputElement).value),1,6)}});};document.querySelectorAll<HTMLInputElement>('[data-combat="weaponAtk"],[data-combat="equipmentDef"]').forEach(i=>{i.disabled=true;i.title="Derived from Active Body by MIRU rules";});if(!state.combat.active&&state.combat.enemyHp===0){const cmd=document.querySelector<HTMLElement>(".combat-command");if(cmd&&!cmd.querySelector("#reward-helper")){const r=actionBox("COMBAT AFTERMATH · p.16",`Roll ${state.combat.enemySkill} D6. Combine dice into reward-pool totals.`);add(r,btn("ROLL REWARD DICE",()=>{if(!state)return;const rolls=Array.from({length:state.combat.enemySkill},d6);void commit({...state,combat:{...state.combat,rewardRolls:rolls,log:[...state.combat.log,`Reward dice: ${rolls.join(", ")}`]}});}));r.id="reward-helper";cmd.appendChild(r);}}}
function patchMap(){if(!state)return;const aside=document.querySelector<HTMLElement>("#map-app aside");if(!aside)return;aside.querySelector("#impassable-edge")?.remove();const selected=aside.querySelector<HTMLElement>(".hex-title b")?.textContent?.trim();if(!selected||selected===state.currentHex)return;const key=edge(state.currentHex,selected),blocked=state.impassableEdges.includes(key),move=aside.querySelector<HTMLButtonElement>("#move");if(move&&blocked){move.disabled=true;move.textContent="IMPASSABLE EDGE";}const b=document.createElement("button");b.id="impassable-edge";b.className="impassable-control";b.textContent=blocked?"CLEAR IMPASSABLE EDGE":"MARK EDGE IMPASSABLE";b.onclick=()=>{if(!state)return;const impassableEdges=blocked?state.impassableEdges.filter(x=>x!==key):[...state.impassableEdges,key];void commit({...state,impassableEdges});};aside.appendChild(b);}
function patch(){if(!state)return;injectStyle();correctPageRefs();patchLoadoutLock();patchGuide();patchCombat();patchMap();}
function queuePatch(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;patch();});}
async function refresh(){state=await loadState();if(await ensureThirdInjury())return;queuePatch();}
window.addEventListener("miru:playdesk-render",()=>void refresh());
OBR.onReady(async()=>{await refresh();OBR.room.onMetadataChange(meta=>{if(meta[META_KEY])void refresh();});const obs=new MutationObserver(()=>queuePatch());obs.observe(document.body,{subtree:true,childList:true});});
