import OBR from "@owlbear-rodeo/sdk";
import type { Weather } from "./rules";

export const META_KEY = "com.esortland.miru-companion/state";
export type Step = "A"|"B"|"C"|"D"|"E"|"F"|"G"|"H"|"I"|"J"|"K"|"L"|"M"|"N"|"O"|"P";
export type EnemyMarker={name:string;level:number};
export type HexInfo={explored?:boolean;terrain?:string;icon?:string;note?:string;visits?:number;enemy?:EnemyMarker};
export type TerrainRollState={day:number;hex:string;result:number;applied:boolean}|null;
export type ArrivalState={day:number;from:string;hex:string;kind:"new"|"old"}|null;
export type SuppliesState={Fruit:number;"Meal Bar":number;Bits:number;Arrows:number};
export type EscapeMoveState={from:string;nextStep:"N"|"O"}|null;
export type DayState={day:number;ate:boolean;foodEaten:number;slept:boolean;sleepPossible:boolean;weather:Weather|null;weatherRoll:number|null;conditionsApplied:boolean;pendingAfterP:"minor-injury-3"|null;escapeMove:EscapeMoveState};
export type CombatState={active:boolean;enemyName:string;enemyHp:number;enemyMaxHp:number;enemyDef:number;enemyEsc:number;enemyAtkLow:number;enemyAtkMid:number;enemyAtkHigh:number;robot:boolean;burn:number;stun:number;weaponAtk:number;equipmentDef:number;selectedWeapon:string|null;enemySkill:number;rewardRolls:number[];enemyAtkBonusNext:number;escapeLocked:boolean;log:string[]};
export type MiruState={version:9;day:number;step:Step;hp:number;ep:number;starvation:number;poison:number;sleepDeprivation:number;minorInjuries:number;currentHex:string;mapHexes:Record<string,HexInfo>;terrainRoll:TerrainRollState;arrival:ArrivalState;dayState:DayState;experiencedEvents:string[];impassableEdges:string[];supplies:SuppliesState;inventory:Record<string,number>;activeBody:string[];mask:string|null;tools:string[];techSkills:Record<string,number>;techUsedDay:Record<string,number>;combat:CombatState;notes:string};

export const DEFAULT_COMBAT:CombatState={active:false,enemyName:"Enemy",enemyHp:10,enemyMaxHp:10,enemyDef:2,enemyEsc:3,enemyAtkLow:0,enemyAtkMid:3,enemyAtkHigh:5,robot:false,burn:0,stun:0,weaponAtk:0,equipmentDef:0,selectedWeapon:null,enemySkill:1,rewardRolls:[],enemyAtkBonusNext:0,escapeLocked:false,log:[]};
export const DEFAULT_STATE:MiruState={version:9,day:1,step:"G",hp:10,ep:10,starvation:0,poison:0,sleepDeprivation:0,minorInjuries:0,currentHex:"G-10",mapHexes:{"G-10":{explored:true,visits:1}},terrainRoll:null,arrival:null,dayState:{day:1,ate:false,foodEaten:0,slept:false,sleepPossible:true,weather:null,weatherRoll:null,conditionsApplied:false,pendingAfterP:null,escapeMove:null},experiencedEvents:[],impassableEdges:[],supplies:{Fruit:0,"Meal Bar":3,Bits:0,Arrows:0},inventory:{},activeBody:[],mask:null,tools:[],techSkills:{},techUsedDay:{},combat:structuredClone(DEFAULT_COMBAT),notes:""};
export function clamp(n:number,lo:number,hi:number){return Math.max(lo,Math.min(hi,n));}
function normalizeRecord(raw:unknown){const out:Record<string,number>={};if(raw&&typeof raw==="object")for(const [k,v] of Object.entries(raw as Record<string,unknown>)){const n=Math.max(0,Math.floor(Number(v))||0);if(n>0)out[k]=n;}return out;}
function normalizeEnemy(raw:unknown):EnemyMarker|undefined{if(!raw||typeof raw!=="object")return;const r=raw as any;const name=typeof r.name==="string"?r.name.trim().slice(0,48):"";if(!name)return;return{name,level:clamp(Math.floor(Number(r.level)||1),1,6)};}
function normalizeMapHexes(raw:unknown){const out:Record<string,HexInfo>={};if(raw&&typeof raw==="object")for(const [key,value] of Object.entries(raw as Record<string,unknown>)){if(!/^[A-G]-\d{2}$/.test(key)||!value||typeof value!=="object")continue;const h=value as any;out[key]={explored:Boolean(h.explored),terrain:typeof h.terrain==="string"?h.terrain.slice(0,32):undefined,icon:typeof h.icon==="string"?h.icon.slice(0,32):undefined,note:typeof h.note==="string"?h.note.slice(0,160):undefined,visits:clamp(Math.floor(Number(h.visits??0)),0,999),enemy:normalizeEnemy(h.enemy)};}out["G-10"]??={explored:true,visits:1};return out;}
function normalizeTerrainRoll(raw:unknown):TerrainRollState{if(!raw||typeof raw!=="object")return null;const r=raw as any,result=Math.floor(Number(r.result)),day=Math.floor(Number(r.day)),hex=typeof r.hex==="string"?r.hex.trim().toUpperCase():"";return result>=1&&result<=6&&day>=1&&/^[A-G]-\d{2}$/.test(hex)?{day:clamp(day,1,66),hex,result,applied:Boolean(r.applied)}:null;}
function normalizeArrival(raw:unknown):ArrivalState{if(!raw||typeof raw!=="object")return null;const r=raw as any,day=Math.floor(Number(r.day)),from=typeof r.from==="string"?r.from.trim().toUpperCase():"",hex=typeof r.hex==="string"?r.hex.trim().toUpperCase():"",kind=r.kind==="new"||r.kind==="old"?r.kind:null;return day>=1&&/^[A-G]-\d{2}$/.test(from)&&/^[A-G]-\d{2}$/.test(hex)&&kind?{day:clamp(day,1,66),from,hex,kind}:null;}
function normalizeCombat(raw:unknown):CombatState{const r=(raw&&typeof raw==="object"?raw:{}) as Partial<CombatState>,maxHp=clamp(Math.floor(Number(r.enemyMaxHp??10))||10,1,999);return{...DEFAULT_COMBAT,...r,active:Boolean(r.active),enemyName:typeof r.enemyName==="string"&&r.enemyName.trim()?r.enemyName.trim().slice(0,48):"Enemy",enemyMaxHp:maxHp,enemyHp:clamp(Math.floor(Number(r.enemyHp??maxHp)),0,maxHp),enemyDef:clamp(Math.floor(Number(r.enemyDef??0)),0,99),enemyEsc:clamp(Math.floor(Number(r.enemyEsc??0)),0,99),enemyAtkLow:clamp(Math.floor(Number(r.enemyAtkLow??0)),0,99),enemyAtkMid:clamp(Math.floor(Number(r.enemyAtkMid??0)),0,99),enemyAtkHigh:clamp(Math.floor(Number(r.enemyAtkHigh??0)),0,99),robot:Boolean(r.robot),burn:clamp(Math.floor(Number(r.burn??0)),0,3),stun:clamp(Math.floor(Number(r.stun??0)),0,3),weaponAtk:clamp(Math.floor(Number(r.weaponAtk??0)),0,99),equipmentDef:clamp(Math.floor(Number(r.equipmentDef??0)),0,99),selectedWeapon:typeof r.selectedWeapon==="string"?r.selectedWeapon.slice(0,48):null,enemySkill:clamp(Math.floor(Number(r.enemySkill??1)),1,6),rewardRolls:Array.isArray(r.rewardRolls)?r.rewardRolls.map(Number).filter(n=>n>=1&&n<=6).slice(0,6):[],enemyAtkBonusNext:clamp(Math.floor(Number(r.enemyAtkBonusNext??0)),0,10),escapeLocked:Boolean(r.escapeLocked),log:Array.isArray(r.log)?r.log.filter((x):x is string=>typeof x==="string").slice(-40):[]};}
function normalizeSupplies(raw:unknown,legacy:Record<string,number>){const r=raw&&typeof raw==="object"?raw as Partial<SuppliesState>:{};const pick=(k:keyof SuppliesState,f=0)=>clamp(Math.floor(Number(r[k]??legacy[k]??f))||0,0,999);return{Fruit:pick("Fruit"),"Meal Bar":pick("Meal Bar",3),Bits:pick("Bits"),Arrows:pick("Arrows")};}
function normalizeEscapeMove(raw:unknown):EscapeMoveState{if(!raw||typeof raw!=="object")return null;const r=raw as any;const from=typeof r.from==="string"?r.from.trim().toUpperCase():"";const nextStep=r.nextStep==="N"||r.nextStep==="O"?r.nextStep:null;return /^[A-G]-\d{2}$/.test(from)&&nextStep?{from,nextStep}:null;}
function normalizeDayState(raw:unknown,day:number):DayState{const r=raw&&typeof raw==="object"?raw as Partial<DayState>:{};const same=Math.floor(Number(r.day))===day;return same?{day,ate:Boolean(r.ate),foodEaten:clamp(Math.floor(Number(r.foodEaten??0)),0,3),slept:Boolean(r.slept),sleepPossible:r.sleepPossible!==false,weather:["Heavy Rain","Harsh Snow","Extreme Winds","Dense Fog","No Weather"].includes(String(r.weather))?r.weather as any:null,weatherRoll:Number(r.weatherRoll)>=1&&Number(r.weatherRoll)<=6?Math.floor(Number(r.weatherRoll)):null,conditionsApplied:Boolean(r.conditionsApplied),pendingAfterP:r.pendingAfterP==="minor-injury-3"?"minor-injury-3":null,escapeMove:normalizeEscapeMove(r.escapeMove)}:{day,ate:false,foodEaten:0,slept:false,sleepPossible:true,weather:null,weatherRoll:null,conditionsApplied:false,pendingAfterP:null,escapeMove:null};}
export function normalizeState(raw:unknown):MiruState{const r=(raw&&typeof raw==="object"?raw:{}) as Partial<MiruState>;const valid:Step[]=["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P"],step=valid.includes(r.step as Step)?r.step as Step:"G",day=clamp(Math.floor(Number(r.day??1)),1,66),legacy=normalizeRecord(r.inventory),supplies=normalizeSupplies(r.supplies,legacy),inventory={...legacy};for(const k of ["Fruit","Meal Bar","Bits","Arrows"])delete inventory[k];let mask=typeof r.mask==="string"&&r.mask.trim()?r.mask.trim().slice(0,48):null;if(!mask&&inventory["Cyclops Mask"]){mask="Cyclops Mask";delete inventory["Cyclops Mask"];}const tools=Array.isArray(r.tools)?[...new Set(r.tools.filter((x):x is string=>typeof x==="string"&&x.trim().length>0))].slice(0,10):[];for(const t of ["Solar Light","Solar Taser"]){if(inventory[t]&&!tools.includes(t))tools.push(t);delete inventory[t];}const activeBody=Array.isArray(r.activeBody)?[...new Set(r.activeBody.filter((x):x is string=>typeof x==="string"&&x.trim().length>0))].filter(x=>!["Fruit","Meal Bar","Bits","Arrows","Cyclops Mask","Solar Light","Solar Taser"].includes(x)).slice(0,5):[];return{...DEFAULT_STATE,version:9,step,day,hp:clamp(Number(r.hp??10),0,20),ep:clamp(Number(r.ep??10),0,20),starvation:clamp(Math.floor(Number(r.starvation??0)),0,8),poison:clamp(Math.floor(Number(r.poison??0)),0,8),sleepDeprivation:clamp(Math.floor(Number(r.sleepDeprivation??0)),0,5),minorInjuries:clamp(Math.floor(Number(r.minorInjuries??0)),0,3),currentHex:typeof r.currentHex==="string"&&r.currentHex.trim()?r.currentHex.trim().toUpperCase():"G-10",mapHexes:normalizeMapHexes(r.mapHexes),terrainRoll:normalizeTerrainRoll(r.terrainRoll),arrival:normalizeArrival(r.arrival),dayState:normalizeDayState(r.dayState,day),experiencedEvents:Array.isArray(r.experiencedEvents)?[...new Set(r.experiencedEvents.filter((x):x is string=>typeof x==="string"&&x.trim().length>0).map(x=>x.trim().slice(0,48)))].slice(0,500):[],impassableEdges:Array.isArray(r.impassableEdges)?[...new Set(r.impassableEdges.filter((x):x is string=>typeof x==="string"&&/^[A-G]-\d{2}\|[A-G]-\d{2}$/.test(x)))]:[],supplies,inventory,activeBody,mask,tools,techSkills:normalizeRecord(r.techSkills),techUsedDay:normalizeRecord(r.techUsedDay),combat:normalizeCombat(r.combat),notes:typeof r.notes==="string"?r.notes.slice(0,4000):""};}
export async function loadState(){const room=await OBR.room.getMetadata(),found=room[META_KEY];if(found)return normalizeState(found);if(await OBR.scene.isReady()){const scene=await OBR.scene.getMetadata(),legacy=scene[META_KEY];if(legacy){const migrated=normalizeState(legacy);await OBR.room.setMetadata({[META_KEY]:migrated});return migrated;}}return structuredClone(DEFAULT_STATE);}
export async function saveState(state:MiruState){await OBR.room.setMetadata({[META_KEY]:normalizeState(state)});}
